#!/usr/bin/env bash
sudo apt install software-properties-common
sudo apt install git
sudo apt-add-repository --yes --update ppa:ansible/ansible
sudo apt install ansible

eval "$(ssh-agent -s)"
ssh-add /home/kaan/.ssh/id_ed25519
