- name: Installing stow
  become: true
  apt: name=stow
  tags:
    - install
    - dotfiles
    - stow
- name: Check if .dotfiles repository exists
  stat:
    path: "{{ lookup('env', 'HOME') }}/.dotfiles"
  register: dotfiles_repo

- name: Start SSH Agent, add key, and clone .dotfiles
  shell: |
    eval "$(ssh-agent -s)"
    ssh-add "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    git clone git@github.com:koyuncukaan/.dotfiles.git "{{ lookup('env', 'HOME') }}/.dotfiles"
  args:
    executable: /bin/bash
  when: not dotfiles_repo.stat.exists
  tags:
    - install
    - dotfiles
    - stow

- name: Check if LazyVim starter exists
  stat:
    path: "{{ lookup('env', 'HOME') }}/.dotfiles/nvim/.config/nvim/init.lua"
  register: lazyvim_repo

- name: Start SSH Agent, add key, and clone lazyvim
  shell: |
    eval "$(ssh-agent -s)"
    ssh-add "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    git clone https://github.com/LazyVim/starter "{{ lookup('env', 'HOME') }}/.dotfiles/nvim/.config/nvim"
  args:
    executable: /bin/bash
  when: not lazyvim_repo.stat.exists
  tags:
    - install
    - dotfiles
    - stow

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./.scripts/ubuntu
  tags:
    - install
    - dotfiles
    - stow

- name: Stow dotfiles
  become_user: kaan
  shell: |
    cd "{{ lookup('env', 'HOME') }}/.dotfiles"
    ./.scripts/ubuntu
  args:
    executable: /bin/zsh
  tags:
    - install
    - dotfiles
    - stow
