- name: Installing stow
  apt: name=stow
  tags:
    - install
    - dotfiles
    - stow
# - name: Cloning .dotfiles
#   ansible.builtin.git:
#     repo: 'git@github.com:koyuncukaan/.dotfiles.git'
#     dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
#     recursive: yes
#     update: yes
#     accept_hostkey: yes
#     version: master
#   tags:
#     - install
#     - dotfiles
#     - stow
# - name: Stow dotfiles
#   shell: cd $HOME/.dotfiles && ./.scripts/ubuntu
#   tags:
#     - install
#     - dotfiles
#     - stow

- name: Stow dotfiles
  become_user: kaan
  environment:
    HOME: /home/kaan
  shell: |
    cd /home/kaan/.dotfiles
    ./.scripts/ubuntu
  args:
    executable: /bin/zsh
  tags:
    - install
    - dotfiles
    - stow
