# - name: Install Yarn
#   npm:
#     name: yarn
#     global: yes
#   tags:
#     - install
#     - node
- name: Install eslint
  npm:
    name: eslint
    global: yes
  become_user: "{{ my_user }}"
  tags:
    - install
    - node
- name: Install Typescript server
  npm:
    name: typescript-language-server
    global: yes
  become_user: "{{ my_user }}"
  tags:
    - install
    - node
- name: Install Typescript
  npm:
    name: typescript
    global: yes
  become_user: "{{ my_user }}"
  tags:
    - install
    - node
- name: Install TS-Node
  npm:
    name: ts-node
    global: yes
  become_user: "{{ my_user }}"
  tags:
    - install
    - node
