- name: Install packages
  become: true
  apt:
    name: [ "tmux", "fzf", "gimp", "xclip", "tldr", "ripgrep", "alacritty","shutter","rofi" ]
  tags:
    - install
    - productivity
# Add the aslatter/ppa repository
- name: Add aslatter/ppa repository
  become: true
  apt_repository:
    repo: ppa:aslatter/ppa
    state: present
  tags:
    - install
    - alacritty

# Install alacritty
- name: Install alacritty
  become: true
  apt:
    name: alacritty
    update_cache: yes  # This ensures the package cache is updated after adding a new repository
    state: present
  tags:
    - install
    - alacritty

- name: Install greenclip
  become: true
  get_url: 
    url: https://github.com/erebe/greenclip/releases/download/v4.2/greenclip
    dest: /usr/local/bin/greenclip
    mode: "0755"  
  tags:
    - install
    - productivity