- name: Install packages
  become: true
  apt:
    name: ["tmux", "fzf", "gimp", "xclip", "tldr", "ripgrep", "rofi"]
  tags:
    - install
    - productivity

- name: Install greenclip
  become: true
  get_url:
    url: https://github.com/erebe/greenclip/releases/download/v4.2/greenclip
    dest: /usr/local/bin/greenclip
    mode: "0755"
  tags:
    - install
    - productivity

