- name: Ensure .ssh directory exists.
  file:
    path: "{{ lookup('env', 'HOME') }}/.ssh"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh

- name: Install ssh key
  copy:
    src: "{{ source_key }}"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh

- name: Install ssh key public
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh

- name: Set authorized key from file
  authorized_key:
    user: "kaan"
    state: present
    key: "{{ lookup('file', item) }}"
  loop: "{{ q('fileglob', lookup('env', 'HOME') ~ '/.ssh/*.pub') }}"
  tags:
    - dotfiles
    - install
    - ssh

- name: Start the SSH Agent
  shell: eval "$(ssh-agent -s)" && ssh-add "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  register: ssh_agent_output
  ignore_errors: true
  tags:
    - ssh

- name: Check if SSH Agent started successfully
  fail:
    msg: "Failed to start SSH Agent"
  when: ssh_agent_output.rc != 0
  tags:
    - ssh
